// Code generated by protoc-gen-go. DO NOT EDIT.
// source: optimus.proto

/*
Package optimus is a generated protocol buffer package.

It is generated from these files:
	optimus.proto

It has these top-level messages:
	Point
	ListOfPoints
	RequestWithId
	ListPointsRequest
*/
package optimus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point_Status int32

const (
	Point_PENDING   Point_Status = 0
	Point_PULLED    Point_Status = 1
	Point_RUNNING   Point_Status = 2
	Point_FAILED    Point_Status = 3
	Point_COMPLETED Point_Status = 4
)

var Point_Status_name = map[int32]string{
	0: "PENDING",
	1: "PULLED",
	2: "RUNNING",
	3: "FAILED",
	4: "COMPLETED",
}
var Point_Status_value = map[string]int32{
	"PENDING":   0,
	"PULLED":    1,
	"RUNNING":   2,
	"FAILED":    3,
	"COMPLETED": 4,
}

func (x Point_Status) String() string {
	return proto.EnumName(Point_Status_name, int32(x))
}
func (Point_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Point struct {
	Project     string       `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	Id          uint64       `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Status      Point_Status `protobuf:"varint,3,opt,name=status,enum=Point_Status" json:"status,omitempty"`
	Coordinate  string       `protobuf:"bytes,4,opt,name=coordinate" json:"coordinate,omitempty"`
	MetricValue string       `protobuf:"bytes,5,opt,name=metric_value,json=metricValue" json:"metric_value,omitempty"`
	Metadata    string       `protobuf:"bytes,6,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Point) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Point) GetStatus() Point_Status {
	if m != nil {
		return m.Status
	}
	return Point_PENDING
}

func (m *Point) GetCoordinate() string {
	if m != nil {
		return m.Coordinate
	}
	return ""
}

func (m *Point) GetMetricValue() string {
	if m != nil {
		return m.MetricValue
	}
	return ""
}

func (m *Point) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type ListOfPoints struct {
	Points []*Point `protobuf:"bytes,1,rep,name=points" json:"points,omitempty"`
}

func (m *ListOfPoints) Reset()                    { *m = ListOfPoints{} }
func (m *ListOfPoints) String() string            { return proto.CompactTextString(m) }
func (*ListOfPoints) ProtoMessage()               {}
func (*ListOfPoints) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListOfPoints) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type RequestWithId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RequestWithId) Reset()                    { *m = RequestWithId{} }
func (m *RequestWithId) String() string            { return proto.CompactTextString(m) }
func (*RequestWithId) ProtoMessage()               {}
func (*RequestWithId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestWithId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListPointsRequest struct {
	HowMany uint32 `protobuf:"varint,1,opt,name=how_many,json=howMany" json:"how_many,omitempty"`
}

func (m *ListPointsRequest) Reset()                    { *m = ListPointsRequest{} }
func (m *ListPointsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPointsRequest) ProtoMessage()               {}
func (*ListPointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListPointsRequest) GetHowMany() uint32 {
	if m != nil {
		return m.HowMany
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterType((*ListOfPoints)(nil), "ListOfPoints")
	proto.RegisterType((*RequestWithId)(nil), "RequestWithId")
	proto.RegisterType((*ListPointsRequest)(nil), "ListPointsRequest")
	proto.RegisterEnum("Point_Status", Point_Status_name, Point_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Optimus service

type OptimusClient interface {
	CreatePoint(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Point, error)
	GetPoint(ctx context.Context, in *RequestWithId, opts ...grpc.CallOption) (*Point, error)
	ListPoints(ctx context.Context, in *ListPointsRequest, opts ...grpc.CallOption) (*ListOfPoints, error)
	ModifyPoint(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Point, error)
}

type optimusClient struct {
	cc *grpc.ClientConn
}

func NewOptimusClient(cc *grpc.ClientConn) OptimusClient {
	return &optimusClient{cc}
}

func (c *optimusClient) CreatePoint(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := grpc.Invoke(ctx, "/Optimus/CreatePoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimusClient) GetPoint(ctx context.Context, in *RequestWithId, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := grpc.Invoke(ctx, "/Optimus/GetPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimusClient) ListPoints(ctx context.Context, in *ListPointsRequest, opts ...grpc.CallOption) (*ListOfPoints, error) {
	out := new(ListOfPoints)
	err := grpc.Invoke(ctx, "/Optimus/ListPoints", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimusClient) ModifyPoint(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := grpc.Invoke(ctx, "/Optimus/ModifyPoint", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Optimus service

type OptimusServer interface {
	CreatePoint(context.Context, *Point) (*Point, error)
	GetPoint(context.Context, *RequestWithId) (*Point, error)
	ListPoints(context.Context, *ListPointsRequest) (*ListOfPoints, error)
	ModifyPoint(context.Context, *Point) (*Point, error)
}

func RegisterOptimusServer(s *grpc.Server, srv OptimusServer) {
	s.RegisterService(&_Optimus_serviceDesc, srv)
}

func _Optimus_CreatePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimusServer).CreatePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Optimus/CreatePoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimusServer).CreatePoint(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _Optimus_GetPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWithId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimusServer).GetPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Optimus/GetPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimusServer).GetPoint(ctx, req.(*RequestWithId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Optimus_ListPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimusServer).ListPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Optimus/ListPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimusServer).ListPoints(ctx, req.(*ListPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Optimus_ModifyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimusServer).ModifyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Optimus/ModifyPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimusServer).ModifyPoint(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

var _Optimus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Optimus",
	HandlerType: (*OptimusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePoint",
			Handler:    _Optimus_CreatePoint_Handler,
		},
		{
			MethodName: "GetPoint",
			Handler:    _Optimus_GetPoint_Handler,
		},
		{
			MethodName: "ListPoints",
			Handler:    _Optimus_ListPoints_Handler,
		},
		{
			MethodName: "ModifyPoint",
			Handler:    _Optimus_ModifyPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optimus.proto",
}

func init() { proto.RegisterFile("optimus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x51, 0xaf, 0x93, 0x30,
	0x18, 0x1d, 0x6c, 0x17, 0x76, 0x3f, 0x2e, 0xcb, 0xec, 0x53, 0xdd, 0x83, 0x17, 0x89, 0x26, 0x3c,
	0x35, 0x71, 0xfe, 0x02, 0xb3, 0xe1, 0x42, 0xc2, 0x18, 0x41, 0xa7, 0x8f, 0x4b, 0x1d, 0x5d, 0x56,
	0x23, 0x14, 0xa1, 0xb8, 0xec, 0xd5, 0xdf, 0xe2, 0x0f, 0x35, 0x6d, 0x51, 0x67, 0x8c, 0x4f, 0xd0,
	0x73, 0x4e, 0xce, 0x39, 0x5f, 0xbf, 0x82, 0x2f, 0x1a, 0xc9, 0xab, 0xbe, 0x23, 0x4d, 0x2b, 0xa4,
	0x08, 0xbf, 0xdb, 0x70, 0x97, 0x0b, 0x5e, 0x4b, 0x84, 0xc1, 0x6d, 0x5a, 0xf1, 0x99, 0x1d, 0x25,
	0xb6, 0x02, 0x2b, 0xba, 0x2f, 0x7e, 0x1d, 0xd1, 0x0c, 0x6c, 0x5e, 0x62, 0x3b, 0xb0, 0xa2, 0x49,
	0x61, 0xf3, 0x12, 0xbd, 0x04, 0xa7, 0x93, 0x54, 0xf6, 0x1d, 0x1e, 0x07, 0x56, 0x34, 0x5b, 0xfa,
	0x44, 0x3b, 0x90, 0x77, 0x1a, 0x2c, 0x06, 0x12, 0x3d, 0x03, 0x38, 0x0a, 0xd1, 0x96, 0xbc, 0xa6,
	0x92, 0xe1, 0x89, 0xf6, 0xbc, 0x41, 0xd0, 0x73, 0x78, 0xa8, 0x98, 0x6c, 0xf9, 0xf1, 0xf0, 0x8d,
	0x7e, 0xe9, 0x19, 0xbe, 0xd3, 0x0a, 0xcf, 0x60, 0x1f, 0x14, 0x84, 0x16, 0x30, 0xad, 0x98, 0xa4,
	0x25, 0x95, 0x14, 0x3b, 0x9a, 0xfe, 0x7d, 0x0e, 0x13, 0x70, 0x4c, 0x20, 0xf2, 0xc0, 0xcd, 0xe3,
	0x6c, 0x9d, 0x64, 0x9b, 0xf9, 0x08, 0x01, 0x38, 0xf9, 0x3e, 0x4d, 0xe3, 0xf5, 0xdc, 0x52, 0x44,
	0xb1, 0xcf, 0x32, 0x45, 0xd8, 0x8a, 0x78, 0xfb, 0x26, 0x51, 0xc4, 0x18, 0xf9, 0x70, 0xbf, 0xda,
	0x6d, 0xf3, 0x34, 0x7e, 0x1f, 0xaf, 0xe7, 0x93, 0x90, 0xc0, 0x43, 0xca, 0x3b, 0xb9, 0x3b, 0xe9,
	0x39, 0x54, 0x73, 0xa7, 0xd1, 0x7f, 0xd8, 0x0a, 0xc6, 0x91, 0xb7, 0x74, 0xcc, 0x80, 0xc5, 0x80,
	0x86, 0x8f, 0xe0, 0x17, 0xec, 0x6b, 0xcf, 0x3a, 0xf9, 0x91, 0xcb, 0x73, 0x52, 0x0e, 0x37, 0x64,
	0xae, 0xcd, 0xe6, 0x65, 0x48, 0xe0, 0x89, 0x32, 0x34, 0x76, 0x83, 0x14, 0x3d, 0x85, 0xe9, 0x59,
	0x5c, 0x0e, 0x15, 0xad, 0xaf, 0x5a, 0xea, 0x17, 0xee, 0x59, 0x5c, 0xb6, 0xb4, 0xbe, 0x2e, 0x7f,
	0x58, 0xe0, 0xee, 0xcc, 0x5e, 0xd0, 0x23, 0x78, 0xab, 0x96, 0x51, 0xc9, 0xcc, 0x5a, 0x86, 0xec,
	0xc5, 0xf0, 0x0d, 0x47, 0xe8, 0x05, 0x4c, 0x37, 0xcc, 0x78, 0xa3, 0x19, 0xf9, 0xab, 0xc8, 0x8d,
	0xea, 0x15, 0xc0, 0x9f, 0x0a, 0x08, 0x91, 0x7f, 0xfa, 0x2c, 0x7c, 0x72, 0x3b, 0x74, 0x38, 0x52,
	0xc9, 0x5b, 0x51, 0xf2, 0xd3, 0xf5, 0x3f, 0xc9, 0x9f, 0x1c, 0xfd, 0x66, 0x5e, 0xff, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xe9, 0x95, 0xf9, 0x19, 0x44, 0x02, 0x00, 0x00,
}
